version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  product-microservice:
    build:
      context: ./product-microservice
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    command: ["python", "app.py"]
